import {
  AlertTriangle, ArrowLeft, ArrowRight, ArrowLeftRight, Shuffle, Book, BookOpen,
  Landmark, BarChart3, CandlestickChart, ScatterChart, BarChart4, LineChart, Check,
  ChevronDown, ChevronRight, ChevronUp, Coins, Gauge, Save, PencilLine, FileBarChart,
  Flag, Globe, Globe2, Info, Lock, Sigma, Grid3x3, Edit, PiggyBank, Receipt, RotateCcw,
  Scale, Telescope, Trash2, TrendingUp, UserCircle, MapPinned, X,
  SlidersHorizontal, AlertOctagon, Split, Atom, Brain, Factory, Building2, Warehouse,
  Calculator, PieChart, Clock, CircleDollarSign, Diamond, Eye, FileText, FileSpreadsheet,
  Filter, FunctionSquare, Gavel, GitBranch, Network, LayoutDashboard, LayoutGrid, Map,
  Radar, BarChart2, Shield, Layers, Layers3, Target, History, MoveRight, Users, Wallet,
  MessageCircleWarning, HelpCircle
} from "lucide-react";

// Bản đồ tên icon Tabler (chuỗi lưu trong dữ liệu section/group) sang icon
// tương ứng của lucide-react — dự án không nạp font Tabler Icons nên các
// icon "ti-*" trước đây không hiển thị.
export const TABLER_ICON_MAP = {
  "ti-alert-triangle": AlertTriangle,
  "ti-arrow-left": ArrowLeft,
  "ti-arrow-right": ArrowRight,
  "ti-arrows-exchange": ArrowLeftRight,
  "ti-arrows-shuffle": Shuffle,
  "ti-book": Book,
  "ti-book-2": BookOpen,
  "ti-building-bank": Landmark,
  "ti-chart-bar": BarChart3,
  "ti-chart-candle": CandlestickChart,
  "ti-chart-dots": ScatterChart,
  "ti-chart-histogram": BarChart4,
  "ti-chart-line": LineChart,
  "ti-check": Check,
  "ti-chevron-down": ChevronDown,
  "ti-chevron-right": ChevronRight,
  "ti-chevron-up": ChevronUp,
  "ti-coin": Coins,
  "ti-coins": Coins,
  "ti-dashboard": Gauge,
  "ti-device-floppy": Save,
  "ti-edit-circle": PencilLine,
  "ti-file-analytics": FileBarChart,
  "ti-flag": Flag,
  "ti-globe": Globe,
  "ti-info-circle": Info,
  "ti-lock": Lock,
  "ti-math-function": Sigma,
  "ti-message-circle-exclamation": MessageCircleWarning,
  "ti-patterning": Grid3x3,
  "ti-pencil": Edit,
  "ti-piggy-bank": PiggyBank,
  "ti-receipt-tax": Receipt,
  "ti-rotate": RotateCcw,
  "ti-scale": Scale,
  "ti-telescope": Telescope,
  "ti-trash": Trash2,
  "ti-trending-up": TrendingUp,
  "ti-user-circle": UserCircle,
  "ti-world": Globe2,
  "ti-world-pin": MapPinned,
  "ti-x": X,
  "ti-adjustments": SlidersHorizontal,
  "ti-alert-hexagon": AlertOctagon,
  "ti-arrows-split": Split,
  "ti-atom": Atom,
  "ti-brain": Brain,
  "ti-building-factory": Factory,
  "ti-building-skyscraper": Building2,
  "ti-building-warehouse": Warehouse,
  "ti-calculator": Calculator,
  "ti-chart-pie": PieChart,
  "ti-clock-dollar": Clock,
  "ti-currency-dollar": CircleDollarSign,
  "ti-diamond": Diamond,
  "ti-eye-check": Eye,
  "ti-file-invoice": FileSpreadsheet,
  "ti-file-text": FileText,
  "ti-filter": Filter,
  "ti-function": FunctionSquare,
  "ti-gavel": Gavel,
  "ti-git-branch": GitBranch,
  "ti-hierarchy-3": Network,
  "ti-layout-dashboard": LayoutDashboard,
  "ti-layout-grid": LayoutGrid,
  "ti-map-2": Map,
  "ti-math-symbols": Sigma,
  "ti-radar-2": Radar,
  "ti-report-analytics": BarChart2,
  "ti-shield-half": Shield,
  "ti-stack-2": Layers,
  "ti-stack-3": Layers3,
  "ti-target-arrow": Target,
  "ti-timeline": History,
  "ti-transition-right": MoveRight,
  "ti-users-group": Users,
  "ti-wallet": Wallet,
  "ti-world-latitude": Globe2,
};

export function FinIcon({ name, size = 16, color, style, className, strokeWidth, title }) {
  const Comp = TABLER_ICON_MAP[name] || HelpCircle;
  return <Comp size={size} color={color} style={style} className={className} strokeWidth={strokeWidth} aria-hidden={title ? undefined : "true"} title={title} />;
}
